spring:
  servlet:
    multipart:
      max-file-size: 128MB
      enabled: 'true'
      max-request-size: 128MB
  h2:
    console:
      path: /h2-console
      enabled: 'true'
      settings:
        web-allow-others: 'true'
  profiles:
    include:
      -oauth
  datasource:
    password: strong123
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    url: jdbc:mysql://strongshopdb.cyfaues5cjxq.ap-northeast-2.rds.amazonaws.com:3306/strongdb?serverTimezone=UTC&characterEncoding=UTF-8
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: create
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: 'true'

